In [6]:
#%2. Direct methods for linear systems of equations
#The purpose of this part of the assignment is to explore computationally Gaussian elimination with pivoting. For that reason you must, first of all:
#• Write a piece of code that implements Gaussian elimination with maximal column pivoting. The code must take as input a matrix A, a vector f, and (possibly) an integer n that indicates the size of these objects. The output must be a vector x where the solution to the system Ax = f is stored.

In [1]:
import numpy as np
def gaussian_elimination_with_pivoting(A, f, n=None):
    if n is None:
        n = A.shape[0]
    A = A.astype(float)  # Ensure A is a float matrix for division operations
    f = f.astype(float)
   
    # Augment the matrix with the vector f
    AugmentedMatrix = np.hstack((A, f.reshape(-1, 1)))
   
    # Gaussian elimination with maximal column pivoting
    for i in range(n):
        # Find the pivot row
        max_row = i + np.argmax(np.abs(AugmentedMatrix[i:, i]))
       
        # Swap the current row with the max_row
        AugmentedMatrix[[i, max_row]] = AugmentedMatrix[[max_row, i]]
       
        # Normalize the pivot row
        AugmentedMatrix[i] = AugmentedMatrix[i] / AugmentedMatrix[i, i]
       
        # Eliminate all rows below the pivot
        for j in range(i + 1, n):
            AugmentedMatrix[j] = AugmentedMatrix[j] - AugmentedMatrix[j, i] * AugmentedMatrix[i]
   
    # Back substitution
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        x[i] = AugmentedMatrix[i, -1] - np.dot(AugmentedMatrix[i, i + 1:n], x[i + 1:n])
   
    return x


In [10]:
# Example usage
A = np.array([[1, 3, 5], [3, 3, 5], [5, 5, 5]])
f = np.array([9, 11, 15])


x = gaussian_elimination_with_pivoting(A, f, n=3)
print(x)

[1. 1. 1.]


In [5]:
def measure_time(n):
    A = create_matrix(n)
    f = create_right_hand_side(n)
    start_time = time.time()
    x = gaussian_elimination_with_pivoting(A, f)
    end_time = time.time()
    return end_time - start_time


In [8]:
import numpy as np

# Define the function to create the matrix
def create_matrix(n):
    A = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            A[i, j] = -1 + 2 * max(i+1, j+1)
    return A  # Ensure the function returns the matrix


In [9]:
# Generate a 10x10 matrix and print it
A = create_matrix(10)
print(A)  # Correct way to print in Python 3

[[ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19.]
 [ 3.  3.  5.  7.  9. 11. 13. 15. 17. 19.]
 [ 5.  5.  5.  7.  9. 11. 13. 15. 17. 19.]
 [ 7.  7.  7.  7.  9. 11. 13. 15. 17. 19.]
 [ 9.  9.  9.  9.  9. 11. 13. 15. 17. 19.]
 [11. 11. 11. 11. 11. 11. 13. 15. 17. 19.]
 [13. 13. 13. 13. 13. 13. 13. 15. 17. 19.]
 [15. 15. 15. 15. 15. 15. 15. 15. 17. 19.]
 [17. 17. 17. 17. 17. 17. 17. 17. 17. 19.]
 [19. 19. 19. 19. 19. 19. 19. 19. 19. 19.]]


In [10]:
x = np.ones((10, 1))

print(x)

Ax = A @ x

print (Ax)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
[[100.]
 [102.]
 [106.]
 [112.]
 [120.]
 [130.]
 [142.]
 [156.]
 [172.]
 [190.]]


In [107]:
import numpy as np
import time

def create_matrix(n):
    A = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            A[i, j] = -1 + 2 * max(i+1, j+1)
    return A

def create_right_hand_side(n):
    A=create_matrix(n)
    f = np.dot(A, np.ones(n))
    return f


def measure_time(n):
    A = create_matrix(n)
    f = create_right_hand_side(n)
    start_time = time.time()
    x = gaussian_elimination_with_pivoting(A, f)
    end_time = time.time()
    return end_time - start_time



In [108]:
A=create_matrix(3)
print(A)

[[1. 3. 5.]
 [3. 3. 5.]
 [5. 5. 5.]]


In [109]:
f=create_right_hand_side(3)
print(f)

[ 9. 11. 15.]


In [110]:
A = create_matrix(3)
f = create_right_hand_side(3)
x = gaussian_elimination_with_pivoting(A, f)
print(x)

[1. 1. 1.]


In [ ]:
size=[10,20,50,100,200,1000,2000]
for n in size:
    A = create_matrix(n)
    f = create_right_hand_side(n)
    start_time = time.time()
    x = gaussian_elimination_with_pivoting(A, f)
    end_time = time.time()
    #print(end_time - start_time)
# Check if the solution is as expected
    if np.allclose(x, np.ones(n)):
        print(f"For n = {n}, the solution is as expected.")
    else:
        print(f"For n = {n}, the solution is incorrect.")

    # Measure time
    time_taken = measure_time(n)
    print(f"Time taken for n = {n}: {time_taken:.4f} seconds")
    print(x)

In [23]:
import numpy as np
import time

def hilbert_matrix(n):
    return np.array([[1 / (i + j - 1) for j in range(1,n+1)] for i in range(1,n+1)], dtype=float)
    return A

def create_right_hand_side(A):
    f = np.sum(A, axis=1)
    return f
    
for n in [4, 8, 12, 14, 16, 18, 20, 50, 100]:
    A = hilbert_matrix(n)
    f = create_right_hand_side(A)
    x = gaussian_elimination_with_pivoting(A, f)

   def measure_time(n):
    A = create_matrix(n)
    f = create_right_hand_side(n)
    start_time = time.time()
    x = gaussian_elimination_with_pivoting(A, f)
    end_time = time.time()
    return end_time - start_time

In [24]:
def hilbert_matrix(n):
    return np.array([[1 / (i + j - 1) for j in range(1,n+1)] for i in range(1,n+1)], dtype=float)
A= hilbert_matrix(2)
print (A)

[[1.         0.5       ]
 [0.5        0.33333333]]


In [26]:
def create_right_hand_sidef(n):
    A= hilbert_matrix(n)
    f = np.sum(A, axis=1)
    return f

A= hilbert_matrix(2)
f = create_right_hand_sidef(2)
print(f)

[1.5        0.83333333]


In [27]:
def measure_timeH(n):
    A = hilbert_matrix(n)
    f = create_right_hand_sidef(n)
    start_time = time.time()
    x = gaussian_elimination_with_pivoting(A, f)
    end_time = time.time()
    return end_time - start_time

In [28]:
x = gaussian_elimination_with_pivoting(A, f)
print(x)

[1. 1.]


In [14]:
size=[4, 8, 12, 14, 16, 18, 20, 50, 100]
for n in size:
    A = hilbert_matrix(n)
    f = create_right_hand_sidef(n)
    x = gaussian_elimination_with_pivoting(A, f)

    # Check if the solution is as expected
    if np.allclose(x, np.ones(n)):
        print(f"For n = {n}, the solution is as expected.")
    else:
        print(f"For n = {n}, the solution is incorrect.")

    # Measure time
    time_taken = measure_timeH(n)
    print(f"Time taken for n = {n}: {time_taken:.4f} seconds")
    print(x)

For n = 4, the solution is as expected.
Time taken for n = 4: 0.0000 seconds
[1. 1. 1. 1.]
For n = 8, the solution is as expected.
Time taken for n = 8: 0.0000 seconds
[1.         1.         0.99999999 1.00000005 0.99999986 1.0000002
 0.99999986 1.00000004]
For n = 12, the solution is incorrect.
Time taken for n = 12: 0.0157 seconds
[0.99999994 1.00000739 0.99977181 1.00306342 0.97781993 1.09642517
 0.73379045 1.47801956 0.44354056 1.40497782 0.83257066 1.03001333]
For n = 14, the solution is incorrect.
Time taken for n = 14: 0.0000 seconds
[ 1.          1.00000087  0.99994483  1.00142895  0.98106681  1.14611705
  0.28978254  3.2776304  -3.93739275  8.27414469 -6.17576521  5.53573515
 -0.66028901  1.26759573]
For n = 16, the solution is incorrect.
Time taken for n = 16: 0.0156 seconds
[ 1.00000006  0.99999044  1.0003918   0.99299066  1.06812913  0.59893992
  2.50977207 -2.68545618  6.58873799 -3.13262104 -0.75561552  8.84763791
 -7.90292548  6.37935433 -0.75181114  1.24248505]
For n = 

In [38]:
import numpy as np

# Function to create matrix A based on the given formula: a_{i,j} = (i - 1)^(j - 1)
def third_matrix_A(n):
    A = np.zeros((n, n))
 
    return np.array([[(i-1) ** ( j - 1) for j in range(1,n+1)] for i in range(1,n+1)], dtype=float)
A= third_matrix(n)
print (A)


# Function to create vector f where f_i = i - 1
def create_vector_f(n):
    f = np.array([i for i in range(n)])
    return f




[[1. 3. 5. 7. 9.]
 [3. 3. 5. 7. 9.]
 [5. 5. 5. 7. 9.]
 [7. 7. 7. 7. 9.]
 [9. 9. 9. 9. 9.]]
Solving for n = 5
Matrix A:
[[  1.   0.   0.   0.   0.]
 [  1.   1.   1.   1.   1.]
 [  1.   2.   4.   8.  16.]
 [  1.   3.   9.  27.  81.]
 [  1.   4.  16.  64. 256.]]
Vector f:
[0 1 2 3 4]
Solution x:
[ 0.  1. -0.  0. -0.]

--------------------------------------------------

Solving for n = 6
Matrix A:
[[1.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00]
 [1.000e+00 1.000e+00 1.000e+00 1.000e+00 1.000e+00 1.000e+00]
 [1.000e+00 2.000e+00 4.000e+00 8.000e+00 1.600e+01 3.200e+01]
 [1.000e+00 3.000e+00 9.000e+00 2.700e+01 8.100e+01 2.430e+02]
 [1.000e+00 4.000e+00 1.600e+01 6.400e+01 2.560e+02 1.024e+03]
 [1.000e+00 5.000e+00 2.500e+01 1.250e+02 6.250e+02 3.125e+03]]
Vector f:
[0 1 2 3 4 5]
Solution x:
[ 0.00000000e+00  1.00000000e+00  1.76363553e-15 -1.00267017e-15
  2.25514052e-16 -1.73472348e-17]

--------------------------------------------------

Solving for n = 7
Matrix A:
[[1.0000

In [44]:
import numpy as np

# Function to create matrix A based on the given formula: a_{i,j} = (i - 1)^(j - 1)
def third_matrix_A(n):
    A = np.zeros((n, n))
    return np.array([[(i-1) ^ ( j - 1) for j in range(1,n+1)] for i in range(1,n+1)], dtype=float)


In [50]:
A= third_matrix_A(5)
print (A)


[[  1.   0.   0.   0.   0.]
 [  1.   1.   1.   1.   1.]
 [  1.   2.   4.   8.  16.]
 [  1.   3.   9.  27.  81.]
 [  1.   4.  16.  64. 256.]]


In [59]:
# Function to create vector f where f_i = i - 1
def create_vectorf_f(n):
    f = np.array([i-1 for i in range(1,n+1)])
    return f

In [60]:
f = create_vectorf_f(5)
print (f)

[0 1 2 3 4]


In [61]:
x = gaussian_elimination_with_pivoting(A, f)
print(x)

[ 0.  1. -0. -0. -0.]


In [62]:
# Testing for different values of n
for n in [5, 6, 7, 10, 12, 15]:
    A = third_matrix_A(n)
    f = create_vectorf_f(n)
    
    print(f"Solving for n = {n}")
    print("Matrix A:")
    print(A)
    print("Vector f:")
    print(f)
    
    # Solve the system
    x = solve_system(A, f)
    
    print("Solution x:")
    print(x)
    print("\n" + "-"*50 + "\n")


Solving for n = 5
Matrix A:
[[  1.   0.   0.   0.   0.]
 [  1.   1.   1.   1.   1.]
 [  1.   2.   4.   8.  16.]
 [  1.   3.   9.  27.  81.]
 [  1.   4.  16.  64. 256.]]
Vector f:
[0 1 2 3 4]
Solution x:
[ 0.  1. -0.  0. -0.]

--------------------------------------------------

Solving for n = 6
Matrix A:
[[1.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00 0.000e+00]
 [1.000e+00 1.000e+00 1.000e+00 1.000e+00 1.000e+00 1.000e+00]
 [1.000e+00 2.000e+00 4.000e+00 8.000e+00 1.600e+01 3.200e+01]
 [1.000e+00 3.000e+00 9.000e+00 2.700e+01 8.100e+01 2.430e+02]
 [1.000e+00 4.000e+00 1.600e+01 6.400e+01 2.560e+02 1.024e+03]
 [1.000e+00 5.000e+00 2.500e+01 1.250e+02 6.250e+02 3.125e+03]]
Vector f:
[0 1 2 3 4 5]
Solution x:
[ 0.00000000e+00  1.00000000e+00  1.76363553e-15 -1.00267017e-15
  2.25514052e-16 -1.73472348e-17]

--------------------------------------------------

Solving for n = 7
Matrix A:
[[1.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00
  0.0000e+00]
 [1.0000e+00 1.00

In [115]:
import numpy as np

def gaussian_elimination_with_swap(A):
    
    n = len(A)
    A = A.astype(float)  # Make sure to work with floating point numbers for division
    row_swap_count = 0  # Counter for row swaps
    
    # Perform Gaussian elimination
    for i in range(n):
        # Pivot: Find the row with the maximum element in column i (for numerical stability)
        max_row = np.argmax(np.abs(A[i:n, i])) + i
        if i != max_row:
            # Swap rows if necessary
            A[[i, max_row]] = A[[max_row, i]]
            row_swap_count += 1
        
        # Eliminate all entries below the pivot element A[i, i]
        for j in range(i + 1, n):
            if A[i, i] == 0:
                raise ValueError("Matrix is singular (determinant is 0).")
            factor = A[j, i] / A[i, i]
            A[j, i:] -= factor * A[i, i:]

    return A, row_swap_count

def det(A):
    """
    Calculate the determinant of matrix A using Gaussian elimination.
    """
    n = len(A)
    A_copy = A.copy()  # Work with a copy of A to avoid modifying the original matrix
    upper_triangular_matrix, row_swap_count = gaussian_elimination_with_swap(A_copy)
    
    # The determinant is the product of the diagonal elements, adjusted for row swaps
    diagonal_product = np.prod(np.diag(upper_triangular_matrix))
    
    # Row swaps flip the sign of the determinant
    determinant = (-1) ** row_swap_count * diagonal_product
    
    return determinant



In [113]:
# Function to create matrix A based on the given formula: a_{i,j} = |i-j|
def fourth_matrix_A(n):
    A = np.zeros((n, n))
    return np.array([[abs(i-j) for j in range(1,n+1)] for i in range(1,n+1)], dtype=float)


In [142]:
# Testing for different values of n
for n in [10,20,100,500]:
    A = fourth_matrix_A(n)
    
    print(f"Solving for n = {n}")
    
    print(A)
    print("Matrix A:")
    determinant = det(A)
    print(f"Determinant of the matrix A: {determinant}")

Solving for n = 5
[[0. 1. 2. 3. 4.]
 [1. 0. 1. 2. 3.]
 [2. 1. 0. 1. 2.]
 [3. 2. 1. 0. 1.]
 [4. 3. 2. 1. 0.]]
Matrix A:
Determinant of the matrix A: 32.0
Solving for n = 10
[[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [1. 0. 1. 2. 3. 4. 5. 6. 7. 8.]
 [2. 1. 0. 1. 2. 3. 4. 5. 6. 7.]
 [3. 2. 1. 0. 1. 2. 3. 4. 5. 6.]
 [4. 3. 2. 1. 0. 1. 2. 3. 4. 5.]
 [5. 4. 3. 2. 1. 0. 1. 2. 3. 4.]
 [6. 5. 4. 3. 2. 1. 0. 1. 2. 3.]
 [7. 6. 5. 4. 3. 2. 1. 0. 1. 2.]
 [8. 7. 6. 5. 4. 3. 2. 1. 0. 1.]
 [9. 8. 7. 6. 5. 4. 3. 2. 1. 0.]]
Matrix A:
Determinant of the matrix A: -2304.000000000001
Solving for n = 20
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
  18. 19.]
 [ 1.  0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16.
  17. 18.]
 [ 2.  1.  0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.
  16. 17.]
 [ 3.  2.  1.  0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14.
  15. 16.]
 [ 4.  3.  2.  1.  0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13.
  14. 

In [94]:
import numpy as np

def fifth_matrix_A(n):
    """
    Create a matrix A where:
    - A[i, j] = 1 if j >= i
    - A[i, j] = -j if j < i

    Parameters:
    - n: The size of the matrix (n x n).

    Returns:
    - A: The matrix of size n x n.
    """
    

    return np.array([[1 if j>= i else -j for j in range(1,n+1)] for i in range(1,n+1)], dtype=float)

# Example usage:
n = 2 # Matrix size (can be adjusted as needed)
A = fifth_matrix_A(n)
print("Matrix A:")
print(A)
determinant = det(A)
print(f"Determinant of the matrix A: {determinant}")

Matrix A:
[[ 1.  1.]
 [-1.  1.]]
Determinant of the matrix A: 2.0


In [119]:
# Testing for different values of n
for n in [10,20,100,500]:
    A = fifth_matrix_A(n)
    
    print(f"Solving for n = {n}")
    
    print(A)
    print("Matrix A:")
    determinant = det(A)
    print(f"Determinant of the matrix A: {determinant}")

Solving for n = 10
[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [-1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [-1. -2.  1.  1.  1.  1.  1.  1.  1.  1.]
 [-1. -2. -3.  1.  1.  1.  1.  1.  1.  1.]
 [-1. -2. -3. -4.  1.  1.  1.  1.  1.  1.]
 [-1. -2. -3. -4. -5.  1.  1.  1.  1.  1.]
 [-1. -2. -3. -4. -5. -6.  1.  1.  1.  1.]
 [-1. -2. -3. -4. -5. -6. -7.  1.  1.  1.]
 [-1. -2. -3. -4. -5. -6. -7. -8.  1.  1.]
 [-1. -2. -3. -4. -5. -6. -7. -8. -9.  1.]]
Matrix A:
Determinant of the matrix A: 3628800.0
Solving for n = 20
[[  1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.
    1.   1.   1.   1.   1.   1.]
 [ -1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.
    1.   1.   1.   1.   1.   1.]
 [ -1.  -2.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.
    1.   1.   1.   1.   1.   1.]
 [ -1.  -2.  -3.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.
    1.   1.   1.   1.   1.   1.]
 [ -1.  -2.  -3.  -4.   1.   1.   1.   1.   1.   1.   1.   1. 

In [121]:
def sixth_matrix_A(n):
    A = np.zeros((n, n), dtype=float)
    A[0, :] = A[:, 0] = 1 / n
    for i in range(1, n):
        for j in range(1, n):
            A[i, j] = A[i-1, j] + A[i, j-1]
    return A

# Example usage:
n = 2 # Matrix size (can be adjusted as needed)
A = sixth_matrix_A(n)
print("Matrix A:")
print(A)
determinant = det(A)
print(f"Determinant of the matrix A: {determinant}")

Matrix A:
[[0.5 0.5]
 [0.5 1. ]]
Determinant of the matrix A: 0.25


In [122]:
# Testing for different values of n
for n in [10,20,100,500]:
    A = sixth_matrix_A(n)
    
    print(f"Solving for n = {n}")
    
    print(A)
    print("Matrix A:")
    determinant = det(A)
    print(f"Determinant of the matrix A: {determinant}")


Solving for n = 10
[[1.000e-01 1.000e-01 1.000e-01 1.000e-01 1.000e-01 1.000e-01 1.000e-01
  1.000e-01 1.000e-01 1.000e-01]
 [1.000e-01 2.000e-01 3.000e-01 4.000e-01 5.000e-01 6.000e-01 7.000e-01
  8.000e-01 9.000e-01 1.000e+00]
 [1.000e-01 3.000e-01 6.000e-01 1.000e+00 1.500e+00 2.100e+00 2.800e+00
  3.600e+00 4.500e+00 5.500e+00]
 [1.000e-01 4.000e-01 1.000e+00 2.000e+00 3.500e+00 5.600e+00 8.400e+00
  1.200e+01 1.650e+01 2.200e+01]
 [1.000e-01 5.000e-01 1.500e+00 3.500e+00 7.000e+00 1.260e+01 2.100e+01
  3.300e+01 4.950e+01 7.150e+01]
 [1.000e-01 6.000e-01 2.100e+00 5.600e+00 1.260e+01 2.520e+01 4.620e+01
  7.920e+01 1.287e+02 2.002e+02]
 [1.000e-01 7.000e-01 2.800e+00 8.400e+00 2.100e+01 4.620e+01 9.240e+01
  1.716e+02 3.003e+02 5.005e+02]
 [1.000e-01 8.000e-01 3.600e+00 1.200e+01 3.300e+01 7.920e+01 1.716e+02
  3.432e+02 6.435e+02 1.144e+03]
 [1.000e-01 9.000e-01 4.500e+00 1.650e+01 4.950e+01 1.287e+02 3.003e+02
  6.435e+02 1.287e+03 2.431e+03]
 [1.000e-01 1.000e+00 5.500e+00 2.20

In [138]:
import numpy as np

def upper_triangular_form(matrix):
   
    # Copy the matrix to avoid modifying the original matrix
    matrix = matrix.astype(float)
    
    n = matrix.shape[0]
    
    # Perform Gaussian elimination
    for i in range(n):
        # Find the pivot row (partial pivoting)
        pivot_row = i
        for j in range(i + 1, n):
            if abs(matrix[j][i]) > abs(matrix[pivot_row][i]):
                pivot_row = j
        
        # Swap rows if necessary
        matrix[[i, pivot_row]] = matrix[[pivot_row, i]]
        
        # Eliminate elements below the pivot
        for j in range(i + 1, n):
            if matrix[i][i] == 0:
                raise ValueError("Matrix is singular and cannot be inverted.")
            factor = matrix[j][i] / matrix[i][i]
            matrix[j] -= factor * matrix[i]
    
    return matrix

def sum_log_abs_diagonal(matrix):
   
    # Get the upper triangular form of the matrix
    upper_triangular = upper_triangular_form(matrix)
    
    # Extract the diagonal entries
    diagonal_entries = np.diag(upper_triangular)
    
    # Calculate the logarithm of the absolute values of the diagonal entries
    log_abs_diagonal = np.log(np.abs(diagonal_entries))
    
    # Return the sum of these logarithms
    return np.sum(log_abs_diagonal)

def calculate_determinant_from_log_sum(matrix):
  
    # Step 1: Sum the logarithms of the absolute diagonal entries
    log_sum = sum_log_abs_diagonal(matrix)
    
    # Step 2: Find the antilog (exponential) of the log_sum to get the determinant
    determinant_abs = np.exp(log_sum)
    
    return determinant_abs

# Example usage:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Calculate the absolute value of the determinant
det_abs = calculate_determinant_from_log_sum(matrix)

print("Absolute value of det(A):", det_abs)


Absolute value of det(A): 6.66133814775094e-16


In [139]:
# Function to create matrix A based on the given formula: a_{i,j} = |i-j|
def fourth_matrix_A(n):
    A = np.zeros((n, n))
    return np.array([[abs(i-j) for j in range(1,n+1)] for i in range(1,n+1)], dtype=float)

In [140]:
A= fourth_matrix_A(5)
print (A)


[[0. 1. 2. 3. 4.]
 [1. 0. 1. 2. 3.]
 [2. 1. 0. 1. 2.]
 [3. 2. 1. 0. 1.]
 [4. 3. 2. 1. 0.]]


In [169]:
# Example usage:
matrix = fourth_matrix_A(500)

# Calculate the absolute value of the determinant
det_abs = calculate_determinant_from_log_sum(matrix)

print("Absolute value of det(A):", det_abs)


Absolute value of det(A): 4.083554783350598e+152


In [165]:
for n in [10, 20, 100, 500]:
    matrix = fourth_matrix_A(n)

    # Calculate the absolute value of the determinant
    det_abs = calculate_determinant_from_log_sum(matrix)

    print(f"Absolute value of det(A) for n={n}: {det_abs:.4e}")

Absolute value of det(A) for n=10: 2.3040e+03
Absolute value of det(A) for n=20: 4.9807e+06
Absolute value of det(A) for n=100: 3.1374e+31
Absolute value of det(A) for n=500: 4.0836e+152


In [171]:
for n in [10, 20, 100, 500]:
    matrix = fifth_matrix_A(n)

    # Calculate the absolute value of the determinant
    det_abs = calculate_determinant_from_log_sum(matrix)

    print(f"Absolute value of det(A) for n={n}: {det_abs:.4e}")


Absolute value of det(A) for n=10: 3.6288e+06
Absolute value of det(A) for n=20: 2.4329e+18
Absolute value of det(A) for n=100: 9.3326e+157
Absolute value of det(A) for n=500: inf


C:\Users\demmanue\AppData\Local\Temp\ipykernel_31800\577938765.py:76: RuntimeWarning: overflow encountered in exp
  determinant_abs = np.exp(log_sum)


In [172]:
for n in [10, 20, 100, 500]:
    matrix = sixth_matrix_A(n)

    # Calculate the absolute value of the determinant
    det_abs = calculate_determinant_from_log_sum(matrix)

    print(f"Absolute value of det(A) for n={n}: {det_abs:.4e}")

Absolute value of det(A) for n=10: 1.0000e-10
Absolute value of det(A) for n=20: 4.7011e-25
Absolute value of det(A) for n=100: inf


C:\Users\demmanue\AppData\Local\Temp\ipykernel_31800\577938765.py:76: RuntimeWarning: overflow encountered in exp
  determinant_abs = np.exp(log_sum)


Absolute value of det(A) for n=500: inf
