In [1]:
import numpy as np

def classical_gram_schmidt(A):
    """
    Perform QR factorization of matrix A using the Classical Gram-Schmidt process.
    
    Parameters:
        A (np.ndarray): Input matrix of shape (m, n).
    
    Returns:
        Q (np.ndarray): Orthonormal matrix with shape (m, n).
        R (np.ndarray): Upper triangular matrix with shape (n, n).
        flag (int): Error flag, 0 if successful, 1 if an error occurs.
    """
    m, n = A.shape
    Q = np.zeros((m, n))  # Orthonormal matrix
    R = np.zeros((n, n))  # Upper triangular matrix
    flag = 0  # Initialize error flag (0 means no error)
    
    for j in range(n):
        # Copy column j of A into vector v
        v = A[:, j]
        
        # Orthogonalization step
        for i in range(j):
            R[i, j] = np.dot(Q[:, i], v)  # Compute projection onto Q[:, i]
            v = v - R[i, j] * Q[:, i]  # Subtract projection from v
        
        # Normalization step
        R[j, j] = np.linalg.norm(v)  # Compute the norm of the vector v
        if R[j, j] < np.finfo(float).eps:  # Check for near-zero pivot
            flag = 1  # Set error flag if linear dependence or instability occurs
            return Q, R, flag
        
        Q[:, j] = v / R[j, j]  # Normalize v to get an orthonormal column in Q
    
    return Q, R, flag


In [10]:
def generate_uniform_matrix(m, n):
    """Generate an m x n matrix with entries uniformly distributed in [0, 1]."""
    return np.random.uniform(0, 1, (m, n))

def generate_custom_matrix(m, n):
    """Generate an m x n matrix with entries a_ij = ((2*i - 21)/19)^(j-1)."""
    A = np.zeros((m, n))
    for i in range(m):
        for j in range(n):
            A[i, j] = ((2 * (i + 1) - 21) / 19) ** (j)
    return A

def generate_hilbert_matrix(m, n):
    # Code to generate an m x n Hilbert matrix
    H = np.array([[1 / (i + j + 1) for j in range(n)] for i in range(m)])
    return H

In [5]:
Q, R, err = classical_gram_schmidt(A)
if err == 1:
    print(f"Error occurred in Classical Gram-Schmidt for {name}")
else:
    print(f"\nResults for")
    print("Q^T * Q:")
    print(np.dot(Q.T, Q))  # This should ideally be close to the identity matrix


Results for
Q^T * Q:
[[ 1.00000000e+00 -5.84694706e-17 -2.11713919e-16  5.41209013e-17
  -3.28872177e-17 -2.80489112e-16 -2.51573657e-16 -1.35022475e-16
  -4.21355055e-17 -6.97597789e-16]
 [-5.84694706e-17  1.00000000e+00  1.06811313e-16 -7.60784164e-17
  -8.50029353e-17  4.64057970e-17 -7.77957456e-17  1.09281621e-16
   1.14028374e-16  1.12714325e-16]
 [-2.11713919e-16  1.06811313e-16  1.00000000e+00  4.20417813e-17
   1.50079335e-16 -8.28928693e-19 -6.76134552e-17  5.25055505e-17
  -1.42749094e-16  1.83957875e-17]
 [ 5.41209013e-17 -7.60784164e-17  4.20417813e-17  1.00000000e+00
   1.63479252e-17  1.11694592e-16 -4.36380144e-17  1.82940379e-16
  -4.19716735e-17 -1.67435209e-17]
 [-3.28872177e-17 -8.50029353e-17  1.50079335e-16  1.63479252e-17
   1.00000000e+00  3.78120734e-17  1.31329598e-16 -4.24375150e-18
   2.23294086e-16  1.52207807e-17]
 [-2.80489112e-16  4.64057970e-17 -8.28928693e-19  1.11694592e-16
   3.78120734e-17  1.00000000e+00 -4.22539873e-17 -1.51635414e-17
  -3.975989

In [3]:
A= generate_uniform_matrix(20, 10)
classical_gram_schmidt(A)

(array([[ 0.33643377,  0.1293123 , -0.04991244, -0.24573336, -0.20768977,
         -0.25166774,  0.32539568, -0.09529423,  0.32735892,  0.00724681],
        [ 0.11029837,  0.34342394, -0.00073449, -0.13447008,  0.32674636,
          0.11252791, -0.00613337, -0.18208409, -0.04953337, -0.02070174],
        [ 0.29500949, -0.16419639, -0.09096351, -0.12738261,  0.01330728,
          0.29997958,  0.43539953, -0.2241236 , -0.24075398, -0.16390212],
        [ 0.08788938,  0.33922486, -0.07860687,  0.01208143,  0.1867219 ,
          0.52939596, -0.10714924, -0.05130679,  0.12400676,  0.49895618],
        [ 0.23207126, -0.00781437, -0.16300584,  0.34019915, -0.14011631,
          0.02574609, -0.2229444 ,  0.17302947, -0.16634054, -0.22458064],
        [ 0.04593282,  0.35733089, -0.17578119,  0.45454576,  0.31280149,
         -0.12463795,  0.09196422, -0.05913021,  0.16790745, -0.09038888],
        [ 0.10584557, -0.09105698,  0.09811472,  0.02408239,  0.18687718,
          0.15016307,  0.2639557

In [6]:
A= generate_custom_matrix(20, 10)
classical_gram_schmidt(A)

(array([[ 0.2236068 , -0.3683942 ,  0.43019174, -0.43760939,  0.40514757,
         -0.34694765,  0.27676848, -0.20629104,  0.14377084, -0.09360962],
        [ 0.2236068 , -0.32961586,  0.29434172, -0.16122451, -0.02132356,
          0.20086443, -0.33503553,  0.40172466, -0.40104498,  0.34980438],
        [ 0.2236068 , -0.29083753,  0.17358614,  0.03838679, -0.23455912,
          0.32260045, -0.2670573 ,  0.09771681,  0.1135033 , -0.29068251],
        [ 0.2236068 , -0.25205919,  0.06792501,  0.1702567 , -0.29309437,
          0.21876678,  0.00085687, -0.22417386,  0.31647389, -0.22982177],
        [ 0.2236068 , -0.21328085, -0.02264167,  0.2434174 , -0.24814766,
          0.0334774 ,  0.21378865, -0.28452836,  0.12218296,  0.1418635 ],
        [ 0.2236068 , -0.17450252, -0.09811391,  0.26690108, -0.14362042,
         -0.13802716,  0.2757688 , -0.12358302, -0.16090761,  0.28879873],
        [ 0.2236068 , -0.13572418, -0.15849169,  0.24973993, -0.01609719,
         -0.24186082,  0.1932238

In [7]:
Q, R, err = classical_gram_schmidt(A)
if err == 1:
    print(f"Error occurred in Classical Gram-Schmidt for {name}")
else:
    print(f"\nResults for")
    print("Q^T * Q:")
    print(np.dot(Q.T, Q))  # This should ideally be close to the identity matrix


Results for
Q^T * Q:
[[ 1.00000000e+00  2.20671722e-18 -1.51242602e-16 -2.67129430e-17
   4.41535697e-16  1.50556160e-16 -7.93781315e-16 -1.38226681e-16
   1.46718423e-15  9.46879578e-16]
 [ 2.20671722e-18  1.00000000e+00 -1.18453600e-17  8.77096112e-17
   1.63817010e-19 -4.62030958e-16 -2.96502066e-16  2.42607100e-15
   1.66751386e-15 -2.83019334e-14]
 [-1.51242602e-16 -1.18453600e-17  1.00000000e+00 -1.24311656e-17
   6.70052630e-16 -1.75533549e-16 -2.63258339e-15  4.16773084e-16
   9.33256973e-15 -6.76637626e-16]
 [-2.67129430e-17  8.77096112e-17 -1.24311656e-17  1.00000000e+00
   1.90847706e-17  3.64838765e-16  1.13223896e-16 -3.81976001e-15
  -8.31096746e-16  2.69641296e-14]
 [ 4.41535697e-16  1.63817010e-19  6.70052630e-16  1.90847706e-17
   1.00000000e+00  8.53761409e-17 -9.75713780e-16 -1.82395505e-16
   5.58691814e-15 -7.04231221e-16]
 [ 1.50556160e-16 -4.62030958e-16 -1.75533549e-16  3.64838765e-16
   8.53761409e-17  1.00000000e+00 -1.16990887e-16 -4.44112933e-17
   1.493661

In [11]:
A= generate_hilbert_matrix(20, 10)
classical_gram_schmidt(A)

(array([[ 7.91519005e-01, -5.56499824e-01,  2.36121646e-01,
         -8.49460811e-02,  2.76055933e-02, -8.27896038e-03,
          2.31188757e-03, -6.03412932e-04,  1.47418380e-04,
         -3.29827447e-05],
        [ 3.95759503e-01,  2.01480278e-01, -6.13359598e-01,
          5.39945880e-01, -3.24875025e-01,  1.56995996e-01,
         -6.48952386e-02,  2.36651935e-02, -7.74201846e-03,
          2.29191697e-03],
        [ 2.63839668e-01,  2.94230248e-01, -3.35343759e-01,
         -1.73296595e-01,  5.12467240e-01, -5.15301165e-01,
          3.55347959e-01, -1.93919212e-01,  8.88273631e-02,
         -3.51993502e-02],
        [ 1.97879751e-01,  2.92632215e-01, -1.23193797e-01,
         -3.58717084e-01,  2.75852001e-01,  1.62556579e-01,
         -4.64650264e-01,  4.87733345e-01, -3.52607295e-01,
          2.00374485e-01],
        [ 1.58303801e-01,  2.72484187e-01,  6.14990118e-03,
         -3.39140494e-01, -2.00417955e-02,  3.72209015e-01,
         -2.12559517e-01, -1.94772563e-01,  4.529442

In [12]:
Q, R, err = classical_gram_schmidt(A)
if err == 1:
    print(f"Error occurred in Classical Gram-Schmidt for {name}")
else:
    print(f"\nResults for")
    print("Q^T * Q:")
    print(np.dot(Q.T, Q))  # This should ideally be close to the identity matrix


Results for
Q^T * Q:
[[ 1.00000000e+00 -1.50253713e-16  8.28773961e-15 -1.07725273e-13
   1.50945643e-12 -2.79213031e-11  5.43998610e-10 -9.49922723e-09
   1.35986500e-07 -1.40519155e-06]
 [-1.50253713e-16  1.00000000e+00 -2.66786195e-15  3.17522538e-14
  -2.53263713e-13  8.36801280e-13  2.85855623e-11 -1.57328371e-09
   7.23823415e-08 -2.97568360e-06]
 [ 8.28773961e-15 -2.66786195e-15  1.00000000e+00 -4.66671488e-15
   7.22966147e-14 -1.15217987e-12  1.46490055e-11  6.58801785e-11
  -1.20945111e-08  5.12603728e-07]
 [-1.07725273e-13  3.17522538e-14 -4.66671488e-15  1.00000000e+00
  -1.12631747e-15 -1.20400899e-15  7.11776769e-13 -1.59562938e-11
  -5.04576547e-10  3.75413272e-08]
 [ 1.50945643e-12 -2.53263713e-13  7.22966147e-14 -1.12631747e-15
   1.00000000e+00 -1.08213116e-16  7.89336771e-15 -3.54648035e-12
   2.23654803e-10 -7.79377234e-09]
 [-2.79213031e-11  8.36801280e-13 -1.15217987e-12 -1.20400899e-15
  -1.08213116e-16  1.00000000e+00  2.99781912e-15 -7.96634821e-14
   8.106795

In [18]:
import numpy as np

def modified_gram_schmidt(A):
    """
    Perform QR factorization of matrix A using the Modified Gram-Schmidt process.
    
    Parameters:
        A (np.ndarray): Input matrix of shape (m, n).
    
    Returns:
        Q (np.ndarray): Orthonormal matrix with shape (m, n).
        R (np.ndarray): Upper triangular matrix with shape (n, n).
        flag (int): Error flag, 0 if successful, 1 if an error occurs (e.g., linear dependency or instability).
    """
    m, n = A.shape
    Q = np.zeros((m, n))  # Matrix to store orthonormal columns
    R = np.zeros((n, n))  # Upper triangular matrix
    
    V = A.copy()  # Work with a copy of A to preserve original input
    
    for i in range(n):
        # Compute the norm of the i-th column of V
        R[i, i] = np.linalg.norm(V[:, i])
        
        # Check if the norm is too small (indicating linear dependence or numerical instability)
        if R[i, i] < np.finfo(float).eps:
            return Q, R, 1  # Return error flag 1 if there's linear dependence or instability
        
        # Normalize the i-th column of V to get the i-th column of Q
        Q[:, i] = V[:, i] / R[i, i]
        
        # Perform orthogonalization for the remaining columns in V
        for j in range(i + 1, n):
            R[i, j] = np.dot(Q[:, i], V[:, j])  # Compute the projection of V[:, j] onto Q[:, i]
            V[:, j] = V[:, j] - R[i, j] * Q[:, i]  # Subtract the projection from V[:, j]
    
    return Q, R, 0  # Return the orthonormal matrix Q, upper triangular matrix R, and success flag 0


In [19]:
A= generate_uniform_matrix(20, 10)
modified_gram_schmidt(A)

(array([[ 3.65981130e-01, -5.46289826e-02, -2.27452894e-04,
         -3.80216754e-01,  1.14701038e-01,  6.49911911e-02,
          5.71933681e-02, -2.64347828e-01, -5.56256136e-01,
         -8.65627185e-02],
        [ 3.20181810e-01, -1.15023076e-01,  5.21969512e-01,
          1.74319074e-01,  2.08426617e-01,  1.95933515e-01,
          6.96880467e-02,  9.21082278e-02, -8.24256024e-02,
          1.81834016e-01],
        [ 2.57012394e-01,  2.04194662e-03, -1.44188241e-01,
          1.06516223e-01, -4.00438030e-01, -1.94609190e-01,
          2.08958603e-01,  2.22516706e-01,  1.25189034e-01,
          1.58082602e-01],
        [ 3.60868997e-01, -5.72838826e-02, -4.46338464e-01,
         -3.29933346e-01,  2.92549319e-01,  1.95645200e-03,
          1.57607019e-01,  6.36811413e-02,  3.24739507e-01,
          9.08028210e-02],
        [ 1.41846784e-02,  2.52617125e-01, -2.04111584e-01,
          2.74294046e-01, -2.10197553e-01,  1.99469738e-01,
         -2.46450338e-01, -3.79353754e-01, -1.239160

In [20]:
Q, R, err = modified_gram_schmidt(A)
if err == 1:
    print(f"Error occurred in Modified Gram-Schmidt for {name}")
else:
    print(f"\nResults for")
    print("Q^T * Q:")
    print(np.dot(Q.T, Q))  # This should ideally be close to the identity matrix


Results for
Q^T * Q:
[[ 1.00000000e+00 -8.00233009e-17 -2.11829731e-16 -1.74601929e-17
  -7.10111127e-18  7.94920310e-17  9.20464437e-17 -1.99180805e-17
   3.20776784e-17  2.27147093e-16]
 [-8.00233009e-17  1.00000000e+00 -3.80112639e-17 -2.97559826e-17
   1.53753378e-17  7.11416585e-17 -1.72627397e-16 -3.72612834e-17
  -3.79937340e-17 -1.07093542e-16]
 [-2.11829731e-16 -3.80112639e-17  1.00000000e+00 -1.41988537e-16
   6.90994742e-17 -4.34685872e-17  6.31596367e-17  1.19692038e-16
   1.02575855e-16  1.60559456e-16]
 [-1.74601929e-17 -2.97559826e-17 -1.41988537e-16  1.00000000e+00
  -8.13164146e-17 -1.31004777e-17  8.97712914e-18 -4.05485760e-17
   3.96027525e-17 -5.26935706e-17]
 [-7.10111127e-18  1.53753378e-17  6.90994742e-17 -8.13164146e-17
   1.00000000e+00  1.02367438e-18 -2.94646476e-17 -8.70984220e-17
   1.51277099e-17  1.22744175e-17]
 [ 7.94920310e-17  7.11416585e-17 -4.34685872e-17 -1.31004777e-17
   1.02367438e-18  1.00000000e+00 -1.08752230e-16  5.78421483e-18
   2.033628

In [21]:
A= generate_custom_matrix(20, 10)
modified_gram_schmidt(A)

(array([[ 0.2236068 , -0.3683942 ,  0.43019174, -0.43760939,  0.40514757,
         -0.34694765,  0.27676848, -0.20629104,  0.14377084, -0.09360962],
        [ 0.2236068 , -0.32961586,  0.29434172, -0.16122451, -0.02132356,
          0.20086443, -0.33503553,  0.40172466, -0.40104498,  0.34980438],
        [ 0.2236068 , -0.29083753,  0.17358614,  0.03838679, -0.23455912,
          0.32260045, -0.2670573 ,  0.09771681,  0.1135033 , -0.29068251],
        [ 0.2236068 , -0.25205919,  0.06792501,  0.1702567 , -0.29309437,
          0.21876678,  0.00085687, -0.22417386,  0.31647389, -0.22982177],
        [ 0.2236068 , -0.21328085, -0.02264167,  0.2434174 , -0.24814766,
          0.0334774 ,  0.21378865, -0.28452836,  0.12218296,  0.1418635 ],
        [ 0.2236068 , -0.17450252, -0.09811391,  0.26690108, -0.14362042,
         -0.13802716,  0.2757688 , -0.12358302, -0.16090761,  0.28879873],
        [ 0.2236068 , -0.13572418, -0.15849169,  0.24973993, -0.01609719,
         -0.24186082,  0.1932238

In [23]:
Q, R, err = modified_gram_schmidt(A)
if err == 1:
    print(f"Error occurred in Modified Gram-Schmidt for {name}")
else:
    print(f"\nResults for")
    print("Q^T * Q:")
    print(np.dot(Q.T, Q))  # This should ideally be close to the identity matrix


Results for
Q^T * Q:
[[ 1.00000000e+00 -1.50253713e-16  8.28773961e-15 -1.07725273e-13
   1.50945643e-12 -2.79213031e-11  5.43998610e-10 -9.49922723e-09
   1.35986500e-07 -1.40519155e-06]
 [-1.50253713e-16  1.00000000e+00 -2.66786195e-15  3.17522538e-14
  -2.53263713e-13  8.36801280e-13  2.85855623e-11 -1.57328371e-09
   7.23823415e-08 -2.97568360e-06]
 [ 8.28773961e-15 -2.66786195e-15  1.00000000e+00 -4.66671488e-15
   7.22966147e-14 -1.15217987e-12  1.46490055e-11  6.58801785e-11
  -1.20945111e-08  5.12603728e-07]
 [-1.07725273e-13  3.17522538e-14 -4.66671488e-15  1.00000000e+00
  -1.12631747e-15 -1.20400899e-15  7.11776769e-13 -1.59562938e-11
  -5.04576547e-10  3.75413272e-08]
 [ 1.50945643e-12 -2.53263713e-13  7.22966147e-14 -1.12631747e-15
   1.00000000e+00 -1.08213116e-16  7.89336771e-15 -3.54648035e-12
   2.23654803e-10 -7.79377234e-09]
 [-2.79213031e-11  8.36801280e-13 -1.15217987e-12 -1.20400899e-15
  -1.08213116e-16  1.00000000e+00  2.99781912e-15 -7.96634821e-14
   8.106795

In [22]:
A= generate_hilbert_matrix(20, 10)
modified_gram_schmidt(A)

(array([[ 7.91519005e-01, -5.56499824e-01,  2.36121646e-01,
         -8.49460811e-02,  2.76055933e-02, -8.27896038e-03,
          2.31188757e-03, -6.03412932e-04,  1.47418380e-04,
         -3.29827447e-05],
        [ 3.95759503e-01,  2.01480278e-01, -6.13359598e-01,
          5.39945880e-01, -3.24875025e-01,  1.56995996e-01,
         -6.48952386e-02,  2.36651935e-02, -7.74201846e-03,
          2.29191697e-03],
        [ 2.63839668e-01,  2.94230248e-01, -3.35343759e-01,
         -1.73296595e-01,  5.12467240e-01, -5.15301165e-01,
          3.55347959e-01, -1.93919212e-01,  8.88273631e-02,
         -3.51993502e-02],
        [ 1.97879751e-01,  2.92632215e-01, -1.23193797e-01,
         -3.58717084e-01,  2.75852001e-01,  1.62556579e-01,
         -4.64650264e-01,  4.87733345e-01, -3.52607295e-01,
          2.00374485e-01],
        [ 1.58303801e-01,  2.72484187e-01,  6.14990118e-03,
         -3.39140494e-01, -2.00417955e-02,  3.72209015e-01,
         -2.12559517e-01, -1.94772563e-01,  4.529442

In [24]:
Q, R, err = modified_gram_schmidt(A)
if err == 1:
    print(f"Error occurred in Modified Gram-Schmidt for {name}")
else:
    print(f"\nResults for")
    print("Q^T * Q:")
    print(np.dot(Q.T, Q))  # This should ideally be close to the identity matrix


Results for
Q^T * Q:
[[ 1.00000000e+00 -1.50253713e-16  8.28773961e-15 -1.07725273e-13
   1.50945643e-12 -2.79213031e-11  5.43998610e-10 -9.49922723e-09
   1.35986500e-07 -1.40519155e-06]
 [-1.50253713e-16  1.00000000e+00 -2.66786195e-15  3.17522538e-14
  -2.53263713e-13  8.36801280e-13  2.85855623e-11 -1.57328371e-09
   7.23823415e-08 -2.97568360e-06]
 [ 8.28773961e-15 -2.66786195e-15  1.00000000e+00 -4.66671488e-15
   7.22966147e-14 -1.15217987e-12  1.46490055e-11  6.58801785e-11
  -1.20945111e-08  5.12603728e-07]
 [-1.07725273e-13  3.17522538e-14 -4.66671488e-15  1.00000000e+00
  -1.12631747e-15 -1.20400899e-15  7.11776769e-13 -1.59562938e-11
  -5.04576547e-10  3.75413272e-08]
 [ 1.50945643e-12 -2.53263713e-13  7.22966147e-14 -1.12631747e-15
   1.00000000e+00 -1.08213116e-16  7.89336771e-15 -3.54648035e-12
   2.23654803e-10 -7.79377234e-09]
 [-2.79213031e-11  8.36801280e-13 -1.15217987e-12 -1.20400899e-15
  -1.08213116e-16  1.00000000e+00  2.99781912e-15 -7.96634821e-14
   8.106795

In [25]:
def householder_qr(A):
    """
    Perform QR factorization using Householder reflections.
   
    Parameters:
        A (np.ndarray): Input matrix of shape (m, n).
   
    Returns:
        Q (np.ndarray): Orthogonal matrix.
        R (np.ndarray): Upper triangular matrix.
    """
    m, n = A.shape
    R = A.copy()
    Q = np.eye(m)
   
    for i in range(n):
        # Compute Householder vector
        x = R[i:, i]
        e1 = np.zeros_like(x)
        e1[0] = np.linalg.norm(x)
        u = x - e1
        v = u / np.linalg.norm(u) if np.linalg.norm(u) != 0 else u
       
        # Householder reflection matrix
        H = np.eye(m)
        H[i:, i:] -= 2.0 * np.outer(v, v)
       
        # Update R and Q
        R = H @ R
        Q = Q @ H.T
   
    return Q, R


In [27]:
A= generate_uniform_matrix(20, 10)
householder_qr(A)

(array([[ 0.32865316, -0.11590217, -0.00758532,  0.28089737,  0.12245199,
         -0.2782449 ,  0.47210561, -0.27153549, -0.37263173, -0.04572559,
         -0.0073471 ,  0.0759211 ,  0.39130035,  0.1354053 ,  0.13635835,
          0.06323019,  0.21939679,  0.09717038, -0.01872449,  0.10876527],
        [ 0.37944709, -0.31961625,  0.16440557, -0.22109227,  0.13584364,
          0.37311812,  0.00449291,  0.27995749, -0.17285303, -0.07195635,
         -0.30176321,  0.1204803 , -0.11534992, -0.10698618,  0.21067654,
         -0.10695607,  0.12670997, -0.22193895,  0.34137065,  0.19706054],
        [ 0.05586135,  0.30143801, -0.00115744, -0.06011099, -0.17580011,
          0.5221041 ,  0.26894471, -0.00866744, -0.15708362, -0.27417638,
         -0.17309245,  0.09798613, -0.12913143,  0.35635097, -0.28240405,
         -0.11235009,  0.12826506,  0.22542221, -0.2508655 , -0.14439134],
        [ 0.11861576,  0.14500301, -0.11518023,  0.33445085,  0.0472749 ,
          0.02025603, -0.18720325, 

In [28]:
A= generate_custom_matrix(20, 10)
classical_gram_schmidt(A)

(array([[ 0.2236068 , -0.3683942 ,  0.43019174, -0.43760939,  0.40514757,
         -0.34694765,  0.27676848, -0.20629104,  0.14377084, -0.09360962],
        [ 0.2236068 , -0.32961586,  0.29434172, -0.16122451, -0.02132356,
          0.20086443, -0.33503553,  0.40172466, -0.40104498,  0.34980438],
        [ 0.2236068 , -0.29083753,  0.17358614,  0.03838679, -0.23455912,
          0.32260045, -0.2670573 ,  0.09771681,  0.1135033 , -0.29068251],
        [ 0.2236068 , -0.25205919,  0.06792501,  0.1702567 , -0.29309437,
          0.21876678,  0.00085687, -0.22417386,  0.31647389, -0.22982177],
        [ 0.2236068 , -0.21328085, -0.02264167,  0.2434174 , -0.24814766,
          0.0334774 ,  0.21378865, -0.28452836,  0.12218296,  0.1418635 ],
        [ 0.2236068 , -0.17450252, -0.09811391,  0.26690108, -0.14362042,
         -0.13802716,  0.2757688 , -0.12358302, -0.16090761,  0.28879873],
        [ 0.2236068 , -0.13572418, -0.15849169,  0.24973993, -0.01609719,
         -0.24186082,  0.1932238

In [29]:
A= generate_hilbert_matrix(20, 10)
householder_qr(A)

(array([[ 7.91519005e-01, -5.56499824e-01,  2.36121646e-01,
         -8.49460811e-02,  2.76055933e-02, -8.27896036e-03,
          2.31188715e-03, -6.03406306e-04,  1.47353832e-04,
         -3.36441153e-05,  1.31032594e-06,  2.24528784e-06,
          3.02901656e-06,  2.86872643e-06,  1.60945518e-06,
         -3.06457203e-07, -2.04084781e-06, -2.58016479e-06,
         -9.10575882e-07,  3.86643401e-06],
        [ 3.95759503e-01,  2.01480278e-01, -6.13359598e-01,
          5.39945880e-01, -3.24875025e-01,  1.56995996e-01,
         -6.48952388e-02,  2.36651977e-02, -7.74209396e-03,
          2.29336462e-03, -1.25278530e-04, -2.04824586e-04,
         -2.64160054e-04, -2.40290668e-04, -1.25537936e-04,
          3.89633464e-05,  1.81429814e-04,  2.17894595e-04,
          6.62744947e-05, -3.44716922e-04],
        [ 2.63839668e-01,  2.94230248e-01, -3.35343759e-01,
         -1.73296595e-01,  5.12467240e-01, -5.15301165e-01,
          3.55347959e-01, -1.93919209e-01,  8.88273022e-02,
         -3.